### ISSUE TITLE
BanHammer can't find the path to the database 

### ISSUE THREAD

**Issue by rustyshakelford2** [grandwazir/BanHammer#101]
After updating to 1.7.9 when banhammer goes to load the database it gives an error and the file path is missing backslashes. This happens whether the file is present or not. 

[02:25:10] [Server thread/INFO]: [BanHammer] Enabling BanHammer v2.4.0
[02:25:10] [Server thread/WARN]: [BanHammer] Saving default configuration to config.yml
[02:25:10] [Server thread/WARN]: [BanHammer] Saving default configuration to database.yml
[02:25:10] [Server thread/ERROR]: Error occurred while enabling BanHammer v2.4.0 (Is it up to date?)
com.avaje.ebeaninternal.server.lib.sql.DataSourceException: java.sql.SQLException: path to 'C:MinecraftDaleTechMinecraftpluginsBanHammer/BanHammer.db': 'C:\Minecraft\DaleTech\Minecraft\MinecraftDaleTechMinecraftpluginsBanHammer' does not exist
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:220) ~[spigot.jar:git-Spigot-1455]
Caused by: java.sql.SQLException: path to 'C:MinecraftDaleTechMinecraftpluginsBanHammer/BanHammer.db': 'C:\Minecraft\DaleTech\Minecraft\MinecraftDaleTechMinecraftpluginsBanHammer' does not exist
    at org.sqlite.Conn.open(Conn.java:103) ~[spigot.jar:git-Spigot-1455]
    at org.sqlite.Conn.<init>(Conn.java:57) ~[spigot.jar:git-Spigot-1455]
    at org.sqlite.JDBC.createConnection(JDBC.java:77) ~[spigot.jar:git-Spigot-1455]
    at org.sqlite.JDBC.connect(JDBC.java:64) ~[spigot.jar:git-Spigot-1455]
    at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.7.0_45]
    at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.7.0_45]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createUnpooledConnection(DataSourcePool.java:396) ~[spigot.jar:git-Spigot-1455]
    ... 22 more

**Comment by grandwazir** [comment]
Thanks for reporting this issue. Would you mind doing a quick test with the last Bukkit recommended build and tell me if the problem persists? I just want to check this is not a Spigot specific issue before continuing. Also version 1.7.9 is quite old. Are you sure you are using that one and not the latest one?

**Comment by rustyshakelford2** [comment]
I meant spigot for minecraft 1.7.9, my bad. I'm using banhammer 2.4.0. I tried with the latest bukkit dev build and got the same error, so I don't think it's a spigot issue. I started the server with all other plugins removed and got the same error. I have another server on the same machine running MCPC-Plus and minecraft 1.7.2, and banhammer works great there. Here is the error from bukkit:

13:50:19] [Server thread/INFO]: [BanHammer] Enabling BanHammer v2.4.0
[13:50:19] [Server thread/ERROR]: Error occurred while enabling BanHammer v2.4.0 (Is it up to date?)
com.avaje.ebeaninternal.server.lib.sql.DataSourceException: java.sql.SQLException: path to 'C:MinecraftDaleTechMinecraftpluginsBanHammer/BanHammer.db': 'C:\Minecraft\DaleTech\Minecraft\MinecraftDaleTechMinecraftpluginsBanHammer' does not exist
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:210) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourceManager.getDataSource(DataSourceManager.java:210) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourceGlobalManager.getDataSource(DataSourceGlobalManager.java:63) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.getDataSourceFromConfig(DefaultServerFactory.java:427) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.setDataSource(DefaultServerFactory.java:388) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:168) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at name.richardson.james.bukkit.banhammer.utilities.persistence.database.AbstractDatabaseLoader.load(AbstractDatabaseLoader.java:146) ~[?:?]
    at name.richardson.james.bukkit.banhammer.utilities.persistence.database.AbstractDatabaseLoader.initalise(AbstractDatabaseLoader.java:75) ~[?:?]
    at name.richardson.james.bukkit.banhammer.BanHammer.loadDatabase(BanHammer.java:155) ~[?:?]
    at name.richardson.james.bukkit.banhammer.BanHammer.onEnable(BanHammer.java:102) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:448) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:382) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
Caused by: java.sql.SQLException: path to 'C:MinecraftDaleTechMinecraftpluginsBanHammer/BanHammer.db': 'C:\Minecraft\DaleTech\Minecraft\MinecraftDaleTechMinecraftpluginsBanHammer' does not exist
    at org.sqlite.Conn.open(Conn.java:103) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.Conn.<init>(Conn.java:57) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.JDBC.createConnection(JDBC.java:77) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.JDBC.connect(JDBC.java:64) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.7.0_45]
    at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.7.0_45]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createUnpooledConnection(DataSourcePool.java:401) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createConnectionForQueue(DataSourcePool.java:607) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:205) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.initialise(DataSourcePool.java:248) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:208) ~[spigot.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    ... 22 more

**Comment by anonsvs** [comment]
I have the same problem with Craftbukkit 1.7.9 and I using banhammer version: 2.4.0
I am anon_yt of bukkit plugin page
Error:
[11:35:34 INFO]: [BanHammer] Enabling BanHammer v2.4.0
[11:35:36 ERROR]: Error occurred while enabling BanHammer v2.4.0 (Is it up to date?)
com.avaje.ebeaninternal.server.lib.sql.DataSourceException: java.sql.SQLException: out of memory
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:210) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourceManager.getDataSource(DataSourceManager.java:210) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourceGlobalManager.getDataSource(DataSourceGlobalManager.java:63) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.getDataSourceFromConfig(DefaultServerFactory.java:427) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.setDataSource(DefaultServerFactory.java:388) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:168) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at name.richardson.james.bukkit.banhammer.utilities.persistence.database.AbstractDatabaseLoader.load(AbstractDatabaseLoader.java:146) ~[?:?]
    at name.richardson.james.bukkit.banhammer.utilities.persistence.database.AbstractDatabaseLoader.initalise(AbstractDatabaseLoader.java:75) ~[?:?]
    at name.richardson.james.bukkit.banhammer.BanHammer.loadDatabase(BanHammer.java:155) ~[?:?]
    at name.richardson.james.bukkit.banhammer.BanHammer.onEnable(BanHammer.java:102) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:448) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:382) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
Caused by: java.sql.SQLException: out of memory
    at org.sqlite.DB.throwex(DB.java:370) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.NestedDB._open(NestedDB.java:74) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.DB.open(DB.java:86) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.Conn.open(Conn.java:140) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.Conn.<init>(Conn.java:57) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.JDBC.createConnection(JDBC.java:77) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at org.sqlite.JDBC.connect(JDBC.java:64) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_05]
    at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[?:1.8.0_05]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createUnpooledConnection(DataSourcePool.java:401) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createConnectionForQueue(DataSourcePool.java:607) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:205) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.initialise(DataSourcePool.java:248) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:208) ~[craftbukkit.jar:git-Bukkit-1.7.2-R0.3-66-g43d8943-b3078jnks]
    ... 22 more

**Comment by rustyshakelford2** [comment]
com.avaje.ebeaninternal.server.lib.sql.DataSourceException: java.sql.SQLException: out of memory
I'm pretty sure you're running out of ram.

**Comment by anonsvs** [comment]
mmmm i only using this plugin how i can out of ram?

**Comment by rustyshakelford2** [comment]
The issue seems to be with the {DIR} variable in the database path in bukkit.yml. For whatever reason the backslashes are stripped out when banhammer registers its path. I was able to work around this by manually setting the path. I changed the bukkit.yml default 'url: jdbc:sqlite:{DIR}{NAME}.db' to 'url: jdbc:sqlite:database\{NAME}.db'. This puts all plugin's .db files in a single folder named database, and banhammer is able to find its database now.

**Comment by justinkruit** [comment]
I got the same issue to, but I can't fix it that way.
Can you please make a new version, grandwazir, that fix that?
