### ISSUE TITLE
Needs UUID Support

### ISSUE THREAD

**Issue by PiLoT-** [grandwazir/BanHammer#109]
using spigot 1.8

**Comment by grandwazir** [comment]
UUID support works in the experimental branch. I assume you are using the latest stable version?

**Comment by PiLoT-** [comment]
i was. but Queueami is on of my mods, if you want to close this you can

**Comment by rustyshakelford2** [comment]
You should upload a release with UUID support to bukkitdev. People who don't know about your github are declaring the plugin dead. Also i'd rather not have to compile it myself.

**Comment by xLRDx** [comment]
Hi i understand that the experimental branch is well experimental. I have built the plugin and thrown it on a test server as and it ends up deleting all of the bans. Is there a way to just migrate the bans to use UUID's instead. Is there an actual experimental build somewhere already built that doesn't have this issue?

**Comment by MarioG1** [comment]
You got the experimental branch build working?

**Comment by xLRDx** [comment]
Mhm was able to ban kick etc just got rid of all the other previous bans

**Comment by PiLoT-** [comment]
@MarioG1 ive got a guy creating a program to convert an old form ban list to a uuid supported one

@QueueAmi

**Comment by MarioG1** [comment]
@xLRDx Can you please paste/sand me an link of the compiled jar. I always get errors on the tests after compiling.

**Comment by PiLoT-** [comment]
@MarioG1 The compiled jar still wont convert old versions of the databse though

**Comment by MarioG1** [comment]
This is not the problem. I'll write an short SQL script which will convert it for me. But this will only work if you also have statistics or any other plugin installed which already saves player names and uuids in an database.

**Comment by xLRDx** [comment]
@MarioG1 I suppose so, as long as it is ok with @grandwazir Will have to wait till I am home though

**Comment by MarioG1** [comment]
@xLRDx Thx.

**Comment by grandwazir** [comment]
@xLRDx It is fine with me as long as people don't expect me to support it. Additionally the bans are not deleted, new database tables are created instead. Your old tables are still there but not used by the experimental version. This is so they can be converted when I finish the conversion part of the plugin.

**Comment by grandwazir** [comment]
I've posted a explanation of what I am hoping to do in #112

**Comment by xLRDx** [comment]
@grandwazir @MarioG1 I have chosen not to share the build due to the fact that I do not wish to be held accountable for any issues that arise. It would be best if we wait for the official build. Truthfully it is not all that hard to build when you have some knowledge in this. It is just a matter of fixing the hiccups caused by certain things.

**Comment by grandwazir** [comment]
A quick update. BanHammer is now working correctly with UUIDs and is also now converting the database to the new format successfully as well. There are still a few minor outstanding issues. 
- Colour issue with most commands (cosmetic but annoying)
- It is a bit noisy when it converts the database - effort to stop that is more than it is worth.

Once I have tracked down the colour issue and made sure there is no dead code I will do a proper release. In the mean time you can get the latest development build here: http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/3.0.0-SNAPSHOT/ban-hammer-3.0.0-20150201.213901-1-shaded.jar

As always, make sure you backup your database before trying this version.

**Comment by rustyshakelford2** [comment]
Thanks for the update! It seems to be mostly working, though when you ban a player it has an error kicking them. If you manually kick them after the ban it does work. 

[Server thread/INFO]: rustyshakelford2 issued server command: /ban -t:1m rustyshakelford2 test
[Craft Scheduler Thread - 14/ERROR]: Could not pass event BanHammerPlayerBannedEvent to BanHammer v3.0.0-SNAPSHOT
Caused by: java.lang.IllegalStateException: Asynchronous player kick!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-d0d1d87-bc03b6f]
    at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:218) ~[spigot.jar:git-Spigot-d0d1d87-bc03b6f]
    at name.richardson.james.bukkit.banhammer.ban.event.PlayerListener.onPlayerBanned(PlayerListener.java:68) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-d0d1d87-bc03b6f]
    ... 12 more

**Comment by xDeeKay** [comment]
Just updated to the version you provided, but I'm given this massive error: http://pastebin.com/bwnv5hRr

**Comment by grandwazir** [comment]
@xDeeKay It is meant to do that. See "It is a bit noisy when it converts the database - effort to stop that is more than it is worth." You shouldn't be getting the persistence exception though. Could you give me a dump of your database to test with please.

**Comment by xDeeKay** [comment]
Oh, yes I was referring to the actual errors. Is Dropbox ok?
[removed]

**Comment by grandwazir** [comment]
@xDeeKay Thanks for the database to test with. I've removed the link from your post now I have downloaded it.

**Comment by sjoerdtim** [comment]
I just tried the jar, and although it doesn't give me any errors, all of the commands just give no response. So any commands like /bh, /ban, etc didn't work.

I was forced to downgrade back to the old version by this, but now tomorrow people will have the ability to bypass my bans by changing name.

**Comment by grandwazir** [comment]
@sjoerdtim If the game does that it means there has been an error loading the plugin and you should check your error log for more details. 

A solution which will work until a proper version is out is to do the following:
- Backup or make a copy of your database
- Export all the bans using the export command
- Clear the database
- Upgrade to the experimental version
- Import all the bans

It will import all bans as permanent bans but it is a short term fix and will keep the server safe. You can then always do a proper upgrade later by restoring the old database and running the plugin to update everything.

**Comment by sjoerdtim** [comment]
@grandwazir tried that and this caused everyone who has ever been banned to be permanently banned.
This means that not only people who are banned right now are banned because of it, but also perm bans someone who, for example, had a one day ban a month ago and has been unbanned for ~29 days already, which means we'd lose most of our server because of bans and we can't use that.

Also some guy at our server has 17 alt accounts and found out about name changing causing unban, so now it's impossible to get rid of him because if we ban an alt he just renames it or switches to the next one and can thus log on with a new name every ~2 days. :/

**Comment by PiLoT-** [comment]
@sjoerdtim ip ban time?

**Comment by sjoerdtim** [comment]
@PiLoT- He's been IP-banned months ago, but a simple VPN or Proxy gets around that.

**Comment by NeonLights10** [comment]
Hey, when I try to enable Banhammer on a clean server (nothing added, I was having issues enabling it with my current server), I get this "character to be escaped is missing" error. Here's the error: http://pastebin.com/T0egpTUj

Hope you can help.

**Comment by xDeeKay** [comment]
@grandwazir Hey, any progress on that db I sent you? Would love to be able to update asap.

**Comment by xDeeKay** [comment]
@grandwazir ?

**Comment by grandwazir** [comment]
Sorry been overcommitted recently. Got some time over the next couple of
days. Will look into it, I haven't forgotten!

**Comment by xDeeKay** [comment]
Aha he lives! No worries.

**Comment by davidlohle** [comment]
Just stopping by to say the death of this plugin is upsetting, as UUID support is critical. It's been a great run, thanks!
