### ISSUE TITLE
Kicks creating an internal error.

### ISSUE THREAD

**Issue by Ghukek** [grandwazir/BanHammer#20]
2012-05-03 11:59:19 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'kick' in plugin BanHammer v1.9.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:103)
at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:34)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:169)
at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key kickcommand-default-reason
at java.util.ResourceBundle.getObject(ResourceBundle.java:393)
at java.util.ResourceBundle.getString(ResourceBundle.java:353)
at name.richardson.james.bukkit.utilities.plugin.SimplePlugin.getMessage(SimplePlugin.java:90)
at name.richardson.james.bukkit.utilities.command.PluginCommand.getMessage(PluginCommand.java:84)
at name.richardson.james.bukkit.banhammer.kick.KickCommand.parseArguments(KickCommand.java:81)
at name.richardson.james.bukkit.utilities.command.PluginCommand.onCommand(PluginCommand.java:148)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
... 14 more

**Comment by grandwazir** [comment]
Thank you for reporting this issue. It has been fixed in the latest version of BanHammer.
