### ISSUE TITLE
NullPointerException on server startup/reload

### ISSUE THREAD

**Issue by haveric** [grandwazir/BanHammer#21]
Here is the error that I am getting when I first start up the server or any time I /reload the server:
2012-05-04 20:20:30 [SEVERE] Error occurred while enabling BanHammer v1.9.1 (Is it up to date?)
java.lang.NullPointerException
    at name.richardson.james.bukkit.banhammer.BanHammer.registerCommands(BanHammer.java:191)
    at name.richardson.james.bukkit.banhammer.BanHammer.onEnable(BanHammer.java:108)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:256)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:238)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

Note that the plugin seems to work fine even with this, but it might be causing problems that I don't know about and it is annoying to see Errors when starting up the server.

I just attempted to replicate this error and it makes no sense...  It only comes up when I have 13 or more plugins on the server (including BanHammer).  It doesn't seem to matter what the plugins are, but it breaks when I add a 13th and doesn't appear when I remove any one of them.  Because of this strange behavior, I'm guessing that it might be a bukkit bug related to registerCommands, but I figured I'd post it here first to give you a chance to figure out what is going on or see if you have any ideas about it.

I am running the latest Beta build of CraftBukkit (#2175) but have seen this on several older builds as well.

If you need any more info, please let me know,
Haveric

**Comment by grandwazir** [comment]
It appears to be having an issue registering one of the final commands which are just quasi-alias to the nested commands. These commands are:
- /ban
- /kick
- /pardon

There should not be a circumstance when this would fail with that error. Could you turn on debugging please and post the output of that when the error occurs. It will help me identify where the problem is. Also try using the above three commands when the error happens so I can work out which one is the issue.

**Comment by haveric** [comment]
It would appear /pardon does not work.

Here is the full startup log: http://pastebin.com/Dty238zk
Here is the chat log in game: http://i.imgur.com/RVZai.png

Also note that when I initially banned tbg10101, it did nothing because he was an op.  Perhaps a different message here would be helpful similar to the kick message saying he is exempt from being kicked.

Let me know if there's anything else I can do to help or any more info you need.

**Comment by grandwazir** [comment]
You have a plugin conflict somewhere. All BanHammer messages start with [BanHammer] so whatever command you used to ban your friend was not the BanHammer command. 

I can see further up you have the ban component for CommandBook enabled. Try disabling this and then try again.

**Comment by haveric** [comment]
Well don't I feel silly now.  Thanks for you time.
