### ISSUE TITLE
Errors with Player-Tracker plugin after banhammer 2.01 upgrade!

### ISSUE THREAD

**Issue by jorgenchr** [grandwazir/BanHammer#32]
2012-08-11 21:10:50 [INFO] [P-Tracker] BanHammer detected, attempting to use as banlist.
2012-08-11 21:10:50 [SEVERE] Error occurred while enabling Player-Tracker v1.3 (Is it up to date?)
java.lang.NoSuchMethodError: name.richardson.james.bukkit.banhammer.BanHammer.getHandler(Ljava/lang/Class;)Lname/richardson/james/bukkit/banhammer/BanHandler;
    at org.LostTheGame.PlayerTracker.Banlist.BanHammerBanlist.<init>(BanHammerBanlist.java:13)
    at org.LostTheGame.PlayerTracker.PlayerTracker.onEnable(PlayerTracker.java:233)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:365)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:265)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:247)
    at net.minecraft.server.MinecraftServer.i(MinecraftServer.java:296)
    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:275)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:225)
    at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:140)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:378)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-08-11 21:10:50 [INFO] [HawkEye] Enabling HawkEye v1.0.7b

**Comment by grandwazir** [comment]
I have made a pull request against P-Tracker which fixes this issue. It is up to the author now to update his plugin.
