### ISSUE TITLE
Could not pass event AsyncPlayerPreLoginEvent

### ISSUE THREAD

**Issue by CyanLights** [grandwazir/BanHammer#39]
Hi,

I'm running a 1.4 bukkit server and this error occasionally happens. Any idea of the cause?

Thank you. Your plugin is still our favorite.

23:20:00 [SEVERE] Could not pass event AsyncPlayerPreLoginEvent to BanHammer v2.
0.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:341)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:459)
        at net.minecraft.server.ThreadLoginVerifier.run(ThreadLoginVerifier.java
:48)
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows
but got [2]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultS
erver.java:1242)
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(D
efaultOrmQuery.java:924)
        at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(Default
ExpressionList.java:217)
        at name.richardson.james.bukkit.banhammer.persistence.PlayerRecord.find(
PlayerRecord.java:57)
        at name.richardson.james.bukkit.banhammer.PlayerListener.isPlayerBanned(
PlayerListener.java:193)
        at name.richardson.james.bukkit.banhammer.PlayerListener.onPlayerLogin(P
layerListener.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
        ... 4 more

**Comment by grandwazir** [comment]
This is a duplicate of #34. It is a rare situation that BanHammer can get itself into. If you follow the instructions in that thread you will be able to solve the problem. 

If you are unable to do that you can email me a copy of your database and I will fix it for you.

Glad to know you still like using my plugin :D

**Comment by CyanLights** [comment]
The issue is resolved. Thanks =)
