### ISSUE TITLE
Error in bh undo

### ISSUE THREAD

**Issue by jaboy** [grandwazir/BanHammer#73]
i got this error when i used bh undo to remove a 1 secound ban from a player (since it was one second it was already expired when i used it

``` java
2013-07-13 20:32:08 [INFO] weboy issued server command: /bh undo
2013-07-13 20:32:08 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'bh' in plugin BanHammer v2.2.6-SNAPSHOT
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
    at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
    at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:964)
    at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:882)
    at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:839)
    at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
    at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
    at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:118)
    at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
    at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
    at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
    at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
    at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from banhammer_bans where id=? and created_at=? and expires_at=? and reason=? and state=? and creator_id=? and player_id=?] bind[null]
    at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:123)
    at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:81)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
    at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:67)
    at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeDeleteBean(DefaultPersistExecute.java:128)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:535)
    at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:557)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:654)
    at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:464)
    at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1831)
    at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1821)
    at name.richardson.james.bukkit.banhammer.persistence.BanRecordManager.delete(BanRecordManager.java:16)
    at name.richardson.james.bukkit.banhammer.ban.UndoCommand.execute(UndoCommand.java:70)
    at name.richardson.james.bukkit.banhammer.utilities.command.CommandManager.onCommand(CommandManager.java:65)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more
```

**Comment by grandwazir** [comment]
Thanks for reporting this bug. It is targeted to be fixed in the next release.

**Comment by grandwazir** [comment]
Please test and see if this bug is now fixed using the development version of BanHammer available [here](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/).

**Comment by jaboy** [comment]
testing it now

**Comment by grandwazir** [comment]
I am assuming this is fixed in the latest version. Let me know by reopening this issue if you have any more problems.
